FROM python:3.12

# Create a non-root user
RUN groupadd --gid 1000 appuser && \
    useradd --uid 1000 --gid appuser --shell /bin/bash --create-home appuser

# Set work dir
WORKDIR /usr/src/Backend

# Copy project files
COPY . .

# Install poetry
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get remove -y curl \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get install -y libmagic1

RUN pip install --no-cache-dir -r requirements.txt

# Change ownership of the app directory to the non-root user
RUN chown -R appuser:appuser /usr/src/Backend
# RUN chown -R appuser:appuser /usr/src/Frontend
# Switch to the non-root user
USER appuser

# Expose port 3000 to the outside
EXPOSE 3000

# Run app.py when the container starts
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "3000", "--workers", "10", "--ssl-keyfile", "./pem_key/key.pem", "--ssl-certfile", "./pem_key/cert.pem"]